/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorial: [{type: 'autogenerated', dirName: 'tutorial'}],
    // sidebar: [{type: 'autogenerated', dirName: '.'}],
    // sidebar: {
    //     "intro": ["intro"],
    // },
    // docs: [
    //     'intro'
    // ]
    foundations: [
        {
            type: 'autogenerated',
            dirName: 'foundations',
        }
    ],
    content: [
        {
            type: 'autogenerated',
            dirName: 'content'
        }
    ],
    components: [
        {
            type: 'autogenerated',
            dirName: 'components'
        }
    ],
    patterns: [
        {
            type: 'autogenerated',
            dirName: 'patterns'
        }
    ],
    resources: [
        {
            type: 'autogenerated',
            dirName: 'resources'
        }
    ]
};

// module.exports = sidebars;
