/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorial: [{
        type: 'autogenerated', dirName: 'tutorial'
    }
        // {
        //     type: 'category',
        //     label: 'Tutorial - Extras',
        //     collapsible: true,
        //     collapsed: false,
        //     items: [
        //         'creating-pages',
        //         {
        //             type: 'category',
        //             label: 'Docs',
        //             items: ['introduction', 'sidebar', 'markdown-features', 'versioning'],
        //         },
        //     ],
        // },

    ],
    // sidebar: [{type: 'autogenerated', dirName: '.'}],
    // sidebar: {
    //     "intro": ["intro"],
    // },
    // docs: [
    //     'intro'
    // ]
    foundations: [
        {
            type: 'autogenerated',
            dirName: 'foundations',
        }
    ],
    content: [
        {
            type: 'autogenerated',
            dirName: 'content'
        }
    ],
    components: [
        {
            type: 'autogenerated',
            dirName: 'components'
        }
    ],
    patterns: [
        {
            type: 'autogenerated',
            dirName: 'patterns'
        }
    ],
    resources: [
        {
            type: 'autogenerated',
            dirName: 'resources'
        }
    ]
};

// module.exports = sidebars;
